# Generated by Django 3.2 on 2021-05-22 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210521_2108'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='jugador',
            table='jugador',
        ),
    ]
