# Generated by Django 3.2 on 2021-05-27 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_authuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participa',
            fields=[
                ('idt', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('idr', models.CharField(db_column='IDR', max_length=10, primary_key=True)),
                ('idj', models.CharField(max_length=150, primary_key=True)),
                ('triunfa', models.CharField(db_column='Triunfa', max_length=1)),
            ],
            options={
                'db_table': 'participa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('idt', models.OneToOneField(db_column='IDT', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='torneos.torneo')),
                ('idj', models.ForeignKey(db_column='IDJ', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, to='users.jugador')),
                ('lugar_alcanzado', models.CharField(blank=True, db_column='Lugar_Alcanzado', max_length=25, null=True)),
            ],
            options={
                'db_table': 'participante',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('idt', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('idr', models.CharField(max_length=10, primary_key=True)),
                ('idp', models.CharField(db_column='IDP', max_length=10, primary_key=True)),
                ('idj1', models.CharField(max_length=150)),
                ('idj2', models.CharField(max_length=150)),
                ('resultado', models.CharField(blank=True, db_column='Resultado', max_length=3, null=True)),
                ('fecha_hora_de_iniciop', models.DateTimeField(blank=True, db_column='Fecha_Hora_de_InicioP', null=True)),
                ('fecha_hora_de_finalizacionp', models.DateTimeField(blank=True, db_column='Fecha_Hora_de_FinalizacionP', null=True)),
            ],
            options={
                'db_table': 'partida',
                'managed': False,
            },
        ),
    ]
