# Generated by Django 3.2 on 2021-05-26 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arquetipo',
            fields=[
                ('ida', models.IntegerField(db_column='IDA', primary_key=True, serialize=False)),
                ('nombrea', models.CharField(db_column='NombreA', max_length=25)),
                ('tier', models.CharField(blank=True, db_column='Tier', max_length=3, null=True)),
            ],
            options={
                'db_table': 'arquetipo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('idd', models.AutoField(db_column='IDD', primary_key=True, serialize=False)),
                ('nombred', models.CharField(db_column='NombreD', max_length=100)),
                ('cantidad_cartas_mazo', models.IntegerField(db_column='Cantidad_Cartas_Mazo')),
                ('cantidad_cartas_mazo_alternativo', models.IntegerField(db_column='Cantidad_Cartas_Mazo_Alternativo')),
                ('cantidad_cartas_mazo_extra', models.IntegerField(db_column='Cantidad_Cartas_Mazo_Extra')),
            ],
            options={
                'db_table': 'deck',
                'managed': False,
            },
        ),
    ]
